### PR TITLE
Linter changes

### PR DESCRIPTION
**Pull request by ricardoul**

### CODE REVIEW

**Comment by vitorpy** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging b99fdf65a0bf3bb7ccec2be138ba5668cac33f83 into 3ba2682d8484981ef19ae24b68ee05eaed99d517 - [view on LGTM.com](https://lgtm.com/projects/g/pillarwallet/pillar-bcx-pubsub/rev/pr-d9ab22b6b478229b0edcc616df9d939e29ab1085)

**new alerts:**

* 1 for Unused variable, import, function or class

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by vitorpy** [comment]
@ricardoul Gosh, it's good to see the results from prettier on this code base. Can you ensure the integration tests are ok? Also, let's cleanup the unused var LGTM identified.

**Comment by ricardoul** [comment]
Yes, all test are passing.
Will do the vars right now

**Comment by vitorpy** [comment]
This pull request **fixes 31 alerts** when merging 5bd808ccf6453addd20e18e07070550cd3881953 into 3ba2682d8484981ef19ae24b68ee05eaed99d517 - [view on LGTM.com](https://lgtm.com/projects/g/pillarwallet/pillar-bcx-pubsub/rev/pr-79e37be491bbca5d339b0fe4e7d489ac1ac91b95)

**fixed alerts:**

* 31 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
